locations:
    pokestop: [540, 1250]   # zoom in as far as it goes, then get the coords around your character's head
    spin_swipe: [150, 1040, 540, 1040]              # Any movement that spins a pokestop
    x_button: [540, 2020]                           # The X or Pokeball bottom-center button
    quest_button: [1000, 1870]                      # The orange button quest
    claim_storage_box: [320, 940, 750, 1030]         # the first CLAIM REWARD! text box (THE QUEST STORAGE ONE!)
    claim_reward_box: [320, 1230, 750, 1310]        # the first CLAIM REWARD! text box (NOT THE QUEST STORAGE ONE!)
                                                    #  you must have at least one pokemon in quest storage.
    exit_encounter: [90, 150]                       # exit button on the pokemon encounter
    im_a_passenger_button_box: [320, 1425, 760, 1490]   # the text on I'M A PASSENGER button
    oh_hatching_box: [430, 430, 700, 640]               # the text Oh? when the egg hatches
                                                        #   (you'll have to wait until it
                                                        #   happens to get the coordinates)
    shop_button_text_box: [440, 1370, 650, 1450]        # The SHOP text (for checking in case we get stuck on the menu)
    bottom_pokestop_bar: [240, 1958, 300, 1985]         # This must be a piece of the bottom curved bar when you open a
                                                        #  pokestop. Preferably, choose a small square from the lighter
                                                        #  top border, tho selecting a huge rectangle will probably work
                                                        #  as well. Whatever you choose, it MUST be able to distinguish
                                                        #  between BLUE (when pokestop is able to be spun) and PURPLE,
                                                        #  just after it was spun.

    second_app_position: [820, 1300]  # where to click to switch to the second app after the app switcher is opened
    character_menu_button: [130, 1980]
    friends_tab: [730, 200]
    friend_position: [540, 800]

waits:
    pokestop: 2
    spin_swipe: 4
    x_button: 2
    im_a_passenger_button_box: 1
    quest_button: 3
    claim_reward_box: 8
    exit_encounter: 3
    second_app_position: 2
    character_menu_button: 3
    friends_tab: 2
    friend_position: 3
    keycode_back: 4

configs:
    # action_each: 2   # execute intended action (trade, )
